import * as XLSX from "xlsx";
import { ParsedAudit } from "./parsedAudit";

// Mirrors the fixed layout generated by the "Audit Intake Template.xlsx"
// builder (excel_template/build_template.py). If that template's layout
// ever changes, these row/column references must be updated to match.
//
// This is one of three formats the upload endpoint understands - see
// parseMsFormsExcel.ts (Group B Microsoft Forms export) and
// parseSpotCheckExcel.ts (Group A multi-showroom spot check workbook).

const TABLE_START_ROW = 13; // 1-indexed, matches build_template.py
const TABLE_END_ROW = 41; // 29 POS items (added Tile Specials Leaflets, A6 Showroom Exclusives Labels, Trustpilot Review Stickers on 14 Aug 2026)

function cellStr(ws: XLSX.WorkSheet, addr: string): string {
  const cell = ws[addr];
  if (!cell) return "";
  if (cell.t === "d" && cell.v instanceof Date) return cell.v.toISOString().slice(0, 10);
  return String(cell.v ?? "").trim();
}

/** True if this workbook looks like the original single-showroom template. */
export function isAuditTemplate(wb: XLSX.WorkBook): boolean {
  return !!wb.Sheets["Audit"];
}

export function parseAuditExcel(buffer: Buffer): ParsedAudit {
  const wb = XLSX.read(buffer, { type: "buffer", cellDates: true });
  const ws = wb.Sheets["Audit"];
  if (!ws) {
    throw new Error('Could not find a sheet named "Audit" in this file. Make sure you\'re uploading the unmodified Audit Intake Template.');
  }

  const showroomName = cellStr(ws, "B3");
  const auditDateRaw = cellStr(ws, "B4");
  const auditType = cellStr(ws, "B5");
  const completedByName = cellStr(ws, "B6");
  const completedByEmail = cellStr(ws, "B7");
  const generalComments = cellStr(ws, "B8");
  const supportRequiredRaw = cellStr(ws, "B9");
  const supportDetails = cellStr(ws, "B10");

  if (!showroomName) {
    throw new Error("Showroom (cell B3) is empty. Please select a showroom before uploading.");
  }

  const lineItems: ParsedAudit["lineItems"] = [];
  for (let row = TABLE_START_ROW; row <= TABLE_END_ROW; row++) {
    const category = cellStr(ws, `A${row}`);
    const posName = cellStr(ws, `B${row}`);
    const conditionStatus = cellStr(ws, `C${row}`);
    const comments = cellStr(ws, `D${row}`);
    if (!posName) continue;
    if (!conditionStatus) {
      throw new Error(`Row ${row} ("${posName}") has no Condition Status selected. Every POS item needs a status before uploading.`);
    }
    lineItems.push({ category, posName, conditionStatus, comments });
  }

  return {
    showroomName,
    auditDate: auditDateRaw || null,
    auditType,
    completedByName,
    completedByEmail,
    generalComments,
    supportRequired: supportRequiredRaw.toLowerCase() === "yes",
    supportDetails,
    lineItems,
  };
}
